language: node_js
node_js:
  - "node"

script: npm run build

before_deploy:
  - npm run copy:fonts
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  github-token: $GITHUB_TOKEN
  on:
    branch: master
